- name: Update packages
  hosts: all
  become: true
  tasks:
    - name: Update packages 
      apt:
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'

    - name: Update packages on CentOS
      yum:
        name: '*'
        state: latest
      when: ansible_distribution == 'CentOS'
      
    - name: Upgrade packages 
      apt:
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'

    - name: Upgrade packages on CentOS
      yum:
        name: '*'
        state: latest
      when: ansible_distribution == 'CentOS'

    - name: Install Apache 
      yum:
        name: httpd
        state: present
      when: ansible_distribution == 'CentOS'
      tags: [centos, apache]

    - name: Start Apache on CentOS
      service:
        name: httpd
        state: started
      when: ansible_distribution == 'CentOS'
      tags: [centos, apache]

    - name: Install apache 
      apt:
        name: apache2
        state: present
      when: ansible_distribution == 'Ubuntu'
      

    - name: Start apache 
      service:
        name: apache2
        state: started
      when: ansible_distribution == 'Ubuntu'

    - name: Copy website files
      copy:
        src: index html
        dest: /var/www/html/index.html
      delegate_to: "{{inventory_hostname}}"


      